config/routes.rb
Rails.application.routes.draw do
  resources :works do
    get :autocomplete_constraction_name, :on => :collection 
  end
   get 'works/autocomplete_constraction_name'
   
  resources :constractions do
    get :autocomplete_constraction_name, :on => :collection 
  end
   
  resources :calendars
  resources :orderers
  resources :staffs

end

app/models/work.rb
class Work < ActiveRecord::Base

	belongs_to :staff
	belongs_to :constraction
	
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  autocomplete :constraction, :name, :full => true
  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:hiduke, :staff_id, :constraction_id, :start_time, :end_time, :work_time, :over_time, :night_time)
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_tag(works_path, :method => "get",  id: "search-form") do %>
<!-- text field tag=action,args,identifier,placeholdertext... -->
<%= text_field_tag :search, params[:search], class: "search-query", placeholder: "namesearch", type: "search", data: {autocomplete: autocomplete_constraction_name_works_path} %>  
<!--<%= submit_tag "Search" %>, id_element: '#works_constraction_id' -->
<%end%>
<script type="text/javascript" charset="utf-8">
  $('#search').bind('railsAutocomplete.select', function(event, data){
  $('#work_constraction_id').val(data.item.id);
  });
  //#search_field_id を 検索用テキストフィールドのIDに
</script>

<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hiduke %><br>
    <%= f.date_select :hiduke %>
  </div>
  <div class="field">
    <%= f.label :staff_id %><br>
    <%= f.number_field :staff_id %>
  </div>
  <div class="field">
    <%= f.label :constraction_id %><br>
    <%= f.number_field :constraction_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :work_time %><br>
    <%= f.text_field :work_time %>
  </div>
  <div class="field">
    <%= f.label :over_time %><br>
    <%= f.text_field :over_time %>
  </div>
  <div class="field">
    <%= f.label :night_time %><br>
    <%= f.text_field :night_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<%= form_tag(works_path, :method => "get", id: "search-form") do %>
<!-- text field tag=action,args,identifier,placeholdertext... -->
<%= text_field_tag :search, params[:search], class: "search-query", placeholder: "namesearch", type: "search", data: {autocomplete: works_autocomplete_constraction_name_path} %>  
<%= submit_tag "Search" %>
<%end%>
<script type="text/javascript" charset="utf-8">
  $('#search').bind('railsAutocomplete.select', function(event, data){
  $('#search-form').submit()
  });
</script>


<p id="notice"><%= notice %></p>

<h1>Listing Works</h1>

<table>
  <thead>
    <tr>
      <th>Hiduke</th>
      <th>Staff</th>
      <th>Constraction</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Work time</th>
      <th>Over time</th>
      <th>Night time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.hiduke %></td>
        <td><%= work.staff_id %></td>
        <td><%= work.constraction_id %></td>
        <td><%= work.start_time %></td>
        <td><%= work.end_time %></td>
        <td><%= work.work_time %></td>
        <td><%= work.over_time %></td>
        <td><%= work.night_time %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hiduke:</strong>
  <%= @work.hiduke %>
</p>

<p>
  <strong>Staff:</strong>
  <%= @work.staff_id %>
</p>

<p>
  <strong>Constraction:</strong>
  <%= @work.constraction_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @work.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @work.end_time %>
</p>

<p>
  <strong>Work time:</strong>
  <%= @work.work_time %>
</p>

<p>
  <strong>Over time:</strong>
  <%= @work.over_time %>
</p>

<p>
  <strong>Night time:</strong>
  <%= @work.night_time %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>