config/routes.rb
Rails.application.routes.draw do
  resources :works do
    get :autocomplete_constraction_name, :on => :collection 
  end
   get 'works/autocomplete_constraction_name'
   
  resources :constractions do
    get :autocomplete_constraction_name, :on => :collection 
  end
   
  resources :calendars
  resources :orderers
  resources :staffs

end

app/controllers/constractions_controller.rb
class ConstractionsController < ApplicationController
  before_action :set_constraction, only: [:show, :edit, :update, :destroy]
  autocomplete :constraction, :name, :full => true
  # GET /constractions
  # GET /constractions.json
  def index
    @constractions = Constraction.all
  end

  # GET /constractions/1
  # GET /constractions/1.json
  def show
  end

  # GET /constractions/new
  def new
    @constraction = Constraction.new
  end

  # GET /constractions/1/edit
  def edit
  end

  # POST /constractions
  # POST /constractions.json
  def create
    @constraction = Constraction.new(constraction_params)

    respond_to do |format|
      if @constraction.save
        format.html { redirect_to @constraction, notice: 'Constraction was successfully created.' }
        format.json { render :show, status: :created, location: @constraction }
      else
        format.html { render :new }
        format.json { render json: @constraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constractions/1
  # PATCH/PUT /constractions/1.json
  def update
    respond_to do |format|
      if @constraction.update(constraction_params)
        format.html { redirect_to @constraction, notice: 'Constraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @constraction }
      else
        format.html { render :edit }
        format.json { render json: @constraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constractions/1
  # DELETE /constractions/1.json
  def destroy
    @constraction.destroy
    respond_to do |format|
      format.html { redirect_to constractions_url, notice: 'Constraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constraction
      @constraction = Constraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constraction_params
      params.require(:constraction).permit(:name, :abbreviation, :kana, :code, :orderer_id, :start_date, :end_date)
    end
end

app/helpers/constractions_helper.rb
module ConstractionsHelper
end

app/views/constractions/_form.html.erb
<%= form_for(@constraction) do |f| %>
  <% if @constraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constraction.errors.count, "error") %> prohibited this constraction from being saved:</h2>

      <ul>
      <% @constraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br>
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :kana %><br>
    <%= f.text_field :kana %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :orderer_id %><br>
    <%= f.number_field :orderer_id %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/constractions/edit.html.erb
<h1>Editing Constraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @constraction %> |
<%= link_to 'Back', constractions_path %>

app/views/constractions/index.html.erb
<%= form_tag(constractions_path, :method => "get",  id: "search-form") do %>
<!-- text field tag=action,args,identifier,placeholdertext... -->
<%= text_field_tag :search, params[:search], class: "search-query", placeholder: "namesearch", type: "search", data: {autocomplete: autocomplete_constraction_name_constractions_path} %>  
<%end%>
<script type="text/javascript" charset="utf-8">
  $('#search').bind('railsAutocomplete.select', function(event, data){
  $('#constraction_id').val(data.item.id);
  alert(data.item.id);
  });
  //#search_field_id を 検索用テキストフィールドのIDに
</script>


<p id="notice"><%= notice %></p>

<h1>Listing Constractions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbreviation</th>
      <th>Kana</th>
      <th>Code</th>
      <th>Orderer</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>s
  </thead>

  <tbody>
    <% @constractions.each do |constraction| %>
      <tr>
        <td><%= constraction.name %></td>
        <td><%= constraction.abbreviation %></td>
        <td><%= constraction.kana %></td>
        <td><%= constraction.code %></td>
        <td><%= constraction.orderer_id %></td>
        <td><%= constraction.start_date %></td>
        <td><%= constraction.end_date %></td>
        <td><%= link_to 'Show', constraction %></td>
        <td><%= link_to 'Edit', edit_constraction_path(constraction) %></td>
        <td><%= link_to 'Destroy', constraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constraction', new_constraction_path %>

app/views/constractions/new.html.erb
<h1>New Constraction</h1>

<%= render 'form' %>

<%= link_to 'Back', constractions_path %>

app/views/constractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @constraction.name %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @constraction.abbreviation %>
</p>

<p>
  <strong>Kana:</strong>
  <%= @constraction.kana %>
</p>

<p>
  <strong>Code:</strong>
  <%= @constraction.code %>
</p>

<p>
  <strong>Orderer:</strong>
  <%= @constraction.orderer_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @constraction.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @constraction.end_date %>
</p>

<%= link_to 'Edit', edit_constraction_path(@constraction) %> |
<%= link_to 'Back', constractions_path %>